// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: proto/testservice/service.proto

package testservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallRequest defines the parameters for a service call
type CallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Behavior directives for this request
	// Format: "latency=100ms,error=0.1,cpu=spike"
	Behavior string `protobuf:"bytes,1,opt,name=behavior,proto3" json:"behavior,omitempty"`
	// Optional metadata to include in response
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request body/payload
	Body          string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_proto_testservice_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_proto_testservice_service_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetBehavior() string {
	if x != nil {
		return x.Behavior
	}
	return ""
}

func (x *CallRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CallRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// ServiceResponse contains the result and call chain information
type ServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service identification
	Service *ServiceInfo `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Request timing
	StartTime string `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration  string `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	// Response details
	Code int32  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Body string `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	// Trace information
	TraceId string `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId  string `protobuf:"bytes,8,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Upstream calls made (recursive)
	UpstreamCalls []*UpstreamCall `protobuf:"bytes,9,rep,name=upstream_calls,json=upstreamCalls,proto3" json:"upstream_calls,omitempty"`
	// Applied behaviors
	BehaviorsApplied []string `protobuf:"bytes,10,rep,name=behaviors_applied,json=behaviorsApplied,proto3" json:"behaviors_applied,omitempty"`
	// URL/method that was called (for gRPC, the full method name)
	Url           string `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_proto_testservice_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_testservice_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceResponse) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ServiceResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ServiceResponse) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *ServiceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ServiceResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ServiceResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ServiceResponse) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *ServiceResponse) GetUpstreamCalls() []*UpstreamCall {
	if x != nil {
		return x.UpstreamCalls
	}
	return nil
}

func (x *ServiceResponse) GetBehaviorsApplied() []string {
	if x != nil {
		return x.BehaviorsApplied
	}
	return nil
}

func (x *ServiceResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ServiceInfo describes the service that handled the request
type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod           string                 `protobuf:"bytes,4,opt,name=pod,proto3" json:"pod,omitempty"`
	Node          string                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_testservice_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_testservice_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceInfo) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *ServiceInfo) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ServiceInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// UpstreamCall represents a call to an upstream service
type UpstreamCall struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri      string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Protocol string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Duration string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Code     int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Error    string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Nested upstream calls
	UpstreamCalls []*UpstreamCall `protobuf:"bytes,7,rep,name=upstream_calls,json=upstreamCalls,proto3" json:"upstream_calls,omitempty"`
	// Applied behaviors
	BehaviorsApplied []string `protobuf:"bytes,8,rep,name=behaviors_applied,json=behaviorsApplied,proto3" json:"behaviors_applied,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpstreamCall) Reset() {
	*x = UpstreamCall{}
	mi := &file_proto_testservice_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamCall) ProtoMessage() {}

func (x *UpstreamCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamCall.ProtoReflect.Descriptor instead.
func (*UpstreamCall) Descriptor() ([]byte, []int) {
	return file_proto_testservice_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpstreamCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpstreamCall) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *UpstreamCall) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UpstreamCall) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *UpstreamCall) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpstreamCall) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpstreamCall) GetUpstreamCalls() []*UpstreamCall {
	if x != nil {
		return x.UpstreamCalls
	}
	return nil
}

func (x *UpstreamCall) GetBehaviorsApplied() []string {
	if x != nil {
		return x.BehaviorsApplied
	}
	return nil
}

var File_proto_testservice_service_proto protoreflect.FileDescriptor

const file_proto_testservice_service_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/testservice/service.proto\x12\vtestservice\"\xbe\x01\n" +
	"\vCallRequest\x12\x1a\n" +
	"\bbehavior\x18\x01 \x01(\tR\bbehavior\x12B\n" +
	"\bmetadata\x18\x02 \x03(\v2&.testservice.CallRequest.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x02\n" +
	"\x0fServiceResponse\x122\n" +
	"\aservice\x18\x01 \x01(\v2\x18.testservice.ServiceInfoR\aservice\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\b \x01(\tR\x06spanId\x12@\n" +
	"\x0eupstream_calls\x18\t \x03(\v2\x19.testservice.UpstreamCallR\rupstreamCalls\x12+\n" +
	"\x11behaviors_applied\x18\n" +
	" \x03(\tR\x10behaviorsApplied\x12\x10\n" +
	"\x03url\x18\v \x01(\tR\x03url\"\x9b\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x04 \x01(\tR\x03pod\x12\x12\n" +
	"\x04node\x18\x05 \x01(\tR\x04node\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\"\x85\x02\n" +
	"\fUpstreamCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12@\n" +
	"\x0eupstream_calls\x18\a \x03(\v2\x19.testservice.UpstreamCallR\rupstreamCalls\x12+\n" +
	"\x11behaviors_applied\x18\b \x03(\tR\x10behaviorsApplied2M\n" +
	"\vTestService\x12>\n" +
	"\x04Call\x12\x18.testservice.CallRequest\x1a\x1c.testservice.ServiceResponseB5Z3github.com/kagenti/kkbase/testapp/proto/testserviceb\x06proto3"

var (
	file_proto_testservice_service_proto_rawDescOnce sync.Once
	file_proto_testservice_service_proto_rawDescData []byte
)

func file_proto_testservice_service_proto_rawDescGZIP() []byte {
	file_proto_testservice_service_proto_rawDescOnce.Do(func() {
		file_proto_testservice_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_testservice_service_proto_rawDesc), len(file_proto_testservice_service_proto_rawDesc)))
	})
	return file_proto_testservice_service_proto_rawDescData
}

var file_proto_testservice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_testservice_service_proto_goTypes = []any{
	(*CallRequest)(nil),     // 0: testservice.CallRequest
	(*ServiceResponse)(nil), // 1: testservice.ServiceResponse
	(*ServiceInfo)(nil),     // 2: testservice.ServiceInfo
	(*UpstreamCall)(nil),    // 3: testservice.UpstreamCall
	nil,                     // 4: testservice.CallRequest.MetadataEntry
}
var file_proto_testservice_service_proto_depIdxs = []int32{
	4, // 0: testservice.CallRequest.metadata:type_name -> testservice.CallRequest.MetadataEntry
	2, // 1: testservice.ServiceResponse.service:type_name -> testservice.ServiceInfo
	3, // 2: testservice.ServiceResponse.upstream_calls:type_name -> testservice.UpstreamCall
	3, // 3: testservice.UpstreamCall.upstream_calls:type_name -> testservice.UpstreamCall
	0, // 4: testservice.TestService.Call:input_type -> testservice.CallRequest
	1, // 5: testservice.TestService.Call:output_type -> testservice.ServiceResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_testservice_service_proto_init() }
func file_proto_testservice_service_proto_init() {
	if File_proto_testservice_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_testservice_service_proto_rawDesc), len(file_proto_testservice_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_testservice_service_proto_goTypes,
		DependencyIndexes: file_proto_testservice_service_proto_depIdxs,
		MessageInfos:      file_proto_testservice_service_proto_msgTypes,
	}.Build()
	File_proto_testservice_service_proto = out.File
	file_proto_testservice_service_proto_goTypes = nil
	file_proto_testservice_service_proto_depIdxs = nil
}
