app:
  name: shopflow-ecommerce
  namespaces:
    - sf-gateway
    - sf-products
    - sf-users
    - sf-shopping
    - sf-orders
    - sf-payments
    - sf-infra
  
  # Provider configuration - defines which ingress and mesh providers to use
  providers:
    ingress: istio-gateway  # Options: gateway-api, istio-gateway, k8s-ingress, openshift-routes, none
    mesh: istio          # Options: istio, linkerd, gateway-api-mesh, none
  
  # Default mesh configuration applied to all services (unless overridden at service level)
  meshDefaults:
    timeout: 5s
    retries:
      attempts: 3
      perTryTimeout: 1s
    circuitBreaker:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
    loadBalancing: ROUND_ROBIN  # Options: ROUND_ROBIN, LEAST_REQUEST, RANDOM, PASSTHROUGH

services:
  # ============================================================================
  # Gateway Layer - Single entry point for all client requests
  # ============================================================================
  - name: api-gateway
    namespace: sf-gateway
    replicas: 3
    protocols: [http]
    upstreams:
      - name: product-catalog
        match: [/api/v1/products, /api/v1/catalog]
      - name: search
        match: [/api/v1/search]
      - name: reviews
        match: [/api/v1/reviews]
      - name: user-management
        match: [/api/v1/account, /api/v1/users]
      - name: shopping-cart
        match: [/api/v1/cart]
      - name: checkout
        match: [/api/v1/checkout]
      - name: order-management
        match: [/api/v1/orders]
    ingress:
      enabled: true
      host: shopflow.local
      tls: true
      paths:
        - /api/v1
    # Override mesh defaults for this critical gateway service
    mesh:
      timeout: 10s  # Longer timeout than default
      retries:
        attempts: 5  # More retries for gateway
        perTryTimeout: 2s
    behavior:
      latency: "5-15ms"
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"

  # ============================================================================
  # Product & Discovery Services - How customers find products
  # ============================================================================
  
  - name: product-catalog
    namespace: sf-products
    replicas: 3
    protocols: [http, grpc]
    upstreams:
      - name: inventory
      - name: search
      - name: message-bus
        path: /events/ProductUpdated
      - name: message-bus
        path: /events/PriceChanged
    behavior:
      latency: "15-50ms"
      errorRate: 0.01
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"

  - name: search
    namespace: sf-products
    replicas: 3
    protocols: [http]
    upstreams: []
    behavior:
      latency: "20-80ms"
      errorRate: 0.015
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
    labels:
      component: search-engine

  - name: inventory
    namespace: sf-products
    replicas: 2
    protocols: [grpc]
    upstreams:
      # Weighted group: one stock reservation outcome per request
      - name: stock-reserved
        service: message-bus
        path: /events/StockReserved
        group: stock-outcome
      - name: stock-failed
        service: message-bus
        path: /events/StockReservationFailed
        group: stock-outcome
      # Independent probability: low stock alert fires 1% of requests
      - name: stock-low
        service: message-bus
        path: /events/StockLevelLow
        probability: 0.01          # 1% independent probability
    behavior:
      latency: "10-40ms"
      errorRate: 0.008
      upstreamWeights:
        stock-reserved: 90         # 90% successful reservation
        stock-failed: 10           # 10% reservation failure
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"

  - name: reviews
    namespace: sf-products
    replicas: 2
    protocols: [http]
    upstreams: []
    behavior:
      latency: "15-60ms"
      errorRate: 0.02
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"

  # ============================================================================
  # User & Account Services - Customer identity and personalization
  # ============================================================================
  
  - name: user-management
    namespace: sf-users
    replicas: 3
    protocols: [http, grpc]
    upstreams: []
    behavior:
      latency: "10-35ms"
      errorRate: 0.005
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
    labels:
      security: high
      pii: enabled

  # ============================================================================
  # Transaction Services - Shopping experience
  # ============================================================================
  
  - name: shopping-cart
    namespace: sf-shopping
    replicas: 3
    protocols: [http]
    upstreams:
      - name: inventory
    behavior:
      latency: "12-45ms"
      errorRate: 0.01
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"

  - name: checkout
    namespace: sf-shopping
    replicas: 3
    protocols: [http, grpc]
    upstreams:
      - name: order-management
    behavior:
      latency: "25-100ms"
      errorRate: 0.008
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
    labels:
      critical: enabled

  # ============================================================================
  # Order & Fulfillment Services - Order processing saga
  # ============================================================================
  
  - name: order-management
    namespace: sf-orders
    replicas: 3
    protocols: [grpc]
    upstreams:
      - name: payment
      - name: inventory
      - name: shipping
    behavior:
      latency: "20-70ms"
      errorRate: 0.01
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
    labels:
      critical: enabled

  - name: shipping
    namespace: sf-orders
    replicas: 2
    protocols: [http]
#    upstreams:
#      - name: message-bus
#        paths: [/events/OrderShipped, /events/OrderDelivered]
    behavior:
      latency: "30-120ms"
      errorRate: 0.015
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"

  # ============================================================================
  # Payment Services - Payment processing
  # ============================================================================
  
  - name: payment
    namespace: sf-payments
    replicas: 3
    protocols: [grpc]
    upstreams:
      # Weighted group: one event is selected per request based on weights
      - name: payment-processed      # Unique ID for behavior targeting
        service: message-bus         # Target service
        path: /events/PaymentProcessed
        group: payment-outcome       # Weighted selection group
      - name: payment-failed
        service: message-bus
        path: /events/PaymentFailed
        group: payment-outcome
      - name: payment-refunded
        service: message-bus
        path: /events/PaymentRefunded
        group: payment-outcome
    behavior:
      latency: "50-200ms"
      errorRate: 0.005
      upstreamWeights:
        payment-processed: 85        # 85% success
        payment-failed: 5            # 5% failure
        payment-refunded: 10         # 10% refund
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
    labels:
      security: high
      critical: enabled
      pci-compliant: enabled

  # ============================================================================
  # Infrastructure Services - Event bus and notifications
  # ============================================================================
  
  - name: message-bus
    namespace: sf-infra
    replicas: 3
    protocols: [http]
    upstreams:
      # Event routing configuration - simulates async event delivery to notification service
      # The message-bus routes incoming events to notification service
      - name: notification
        match: [/events/OrderCreated, /events/OrderUpdated, /events/OrderCancelled]
      - name: notification
        match: [/events/PaymentProcessed, /events/PaymentFailed, /events/PaymentRefunded]
      - name: notification
        match: [/events/StockReserved, /events/StockReservationFailed, /events/StockLevelLow]
      - name: notification
        match: [/events/OrderShipped, /events/OrderDelivered]
      - name: notification
        match: [/events/ProductUpdated, /events/PriceChanged]
    behavior:
      latency: "2-10ms"
      errorRate: 0.002
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
    labels:
      component: event-bus
      critical: enabled

  - name: notification
    namespace: sf-infra
    replicas: 2
    protocols: [http]
    upstreams: []
    # Example: Explicitly disable mesh for legacy service if needed
    # mesh:
    #   enabled: false
    behavior:
      latency: "80-250ms"
      errorRate: 0.02
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"
    labels:
      component: notification-service

traffic:
  # Simulate realistic user traffic with daily patterns across multiple endpoints
  - name: web-traffic
    target: api-gateway
    rate: "200/s"
    pattern: diurnal
    duration: 24h
    paths:
      - /api/v1/products
      - /api/v1/catalog
      - /api/v1/search
      - /api/v1/cart
      - /api/v1/checkout
    pathPattern: round-robin

  # Simulate batch processing or API integrations with spiky traffic
  - name: batch-traffic
    target: api-gateway
    rate: "100/s"
    pattern: spiky
    duration: 2h
    paths:
      - /api/v1/orders
      - /api/v1/reviews
    pathPattern: random

  # Constant background load for monitoring
  - name: healthcheck-traffic
    target: api-gateway
    rate: "10/s"
    pattern: steady
    duration: 5m
    paths:
      - /api/v1/catalog
      - /api/v1/search
    pathPattern: round-robin

